### ISSUE TITLE
JSON.stringify() range error - invalid string length

### ISSUE THREAD

**Issue by josh-channin** [freaktechnik/twitch-chatlog#157]
When attempting to fetch a chatlog for a VOD with over ~600k-700k+ chats, e.g. a 24 hour XQC VOD (888381698), the following error is thrown. 

```
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at C:\....\node_modules\twitch-chatlog\bin\twitch-chatlog:90:21
```

This appears to be the max string size or max possible string size that can be "stringified"

**Comment by freaktechnik** [comment]
Thank you for the report. A workaround for now would be to call the CLI with smaller time ranges and then assemble in your consumer.

**Comment by freaktechnik** [comment]
https://www.npmjs.com/package/bfj seems like a package that woukd fit the needs quite well. Will have to experiment with its performance and if I can twek it, since blocking the event loop isn't a concern.

**Comment by josh-channin** [comment]
Awesome news, thanks!

**Comment by freaktechnik** [comment]
This is now implemented in the main branch. However, there's no release yet, since I also need to update the tests. I'll publish a release once that's done. If you feel adventurous (it should be fine, but I haven't checked if I can load the _entire_ VOD for the example you posted, then I wouldn't even have an implementation yet ;) ) you can of course use the state in the main branch for now.

**Comment by freaktechnik** [comment]
And there you are, now available from NPM.
